#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import csv
import json
from pathlib import Path

from transformers import AutoTokenizer


def parse_args():
    parser = argparse.ArgumentParser(
        description="Calculate token length of text field in jsonl files."
    )
    parser.add_argument(
        "--jsonl_data_dir",
        default="data-json/macslu",
        help="Directory containing jsonl files generated by run_macslu.sh stage 0.",
    )
    parser.add_argument(
        "--jsonl_files",
        nargs="+",
        default=["train.jsonl", "dev.jsonl", "test.jsonl"],
        help="Jsonl file names under jsonl_data_dir.",
    )
    parser.add_argument(
        "--model_path",
        default="Qwen/Qwen3-ASR-0.6B",
        help="Hugging Face model path for tokenizer loading.",
    )
    parser.add_argument(
        "--output_csv",
        default="text_token_length.csv",
        help="Output csv path. Relative path is resolved from cwd.",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    data_dir = Path(args.jsonl_data_dir)
    output_csv = Path(args.output_csv)

    tokenizer = AutoTokenizer.from_pretrained(args.model_path, trust_remote_code=True)

    rows = []
    for jsonl_name in args.jsonl_files:
        jsonl_path = data_dir / jsonl_name
        if not jsonl_path.exists():
            raise FileNotFoundError(f"Jsonl file not found: {jsonl_path}")

        set_name = Path(jsonl_name).name
        with jsonl_path.open("r", encoding="utf-8") as f:
            for line_no, line in enumerate(f, start=1):
                if not line.strip():
                    continue
                sample = json.loads(line)
                if "id" not in sample:
                    raise KeyError(f"Missing 'id' in {jsonl_path}:{line_no}")
                if "text" not in sample:
                    raise KeyError(f"Missing 'text' in {jsonl_path}:{line_no}")

                text = sample["text"]
                if not isinstance(text, str):
                    text = str(text)

                token_ids = tokenizer.encode(text, add_special_tokens=False)
                tokens = tokenizer.convert_ids_to_tokens(token_ids)

                rows.append(
                    {
                        "id": sample["id"],
                        "text": text,
                        "text_tokenized": " ".join(tokens),
                        "length": len(token_ids),
                        "set": set_name,
                    }
                )

    output_csv.parent.mkdir(parents=True, exist_ok=True) if output_csv.parent != Path("") else None
    with output_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["id", "text", "text_tokenized", "length", "set"],
        )
        writer.writeheader()
        writer.writerows(rows)

    print(f"Wrote {len(rows)} rows to {output_csv}")


if __name__ == "__main__":
    main()
